"""Add task priority

Revision ID: 8fc07d24f988
Revises: fc1d00a5b271
Create Date: 2026-09-03 10:49:04.607458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc07d24f988'
down_revision: Union[str, Sequence[str], None] = 'fc1d00a5b271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.String(length=50), nullable=False , server_default='medium'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
