"""003_add_client_name

Revision ID: d00bc0b48ff3
Revises: a2dfe78749d3
Create Date: 2026-08-26 13:36:23.041772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00bc0b48ff3'
down_revision: Union[str, Sequence[str], None] = 'a2dfe78749d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('client_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'client_name')
    # ### end Alembic commands ###
